# Generated by Django 3.1.4 on 2020-12-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='rel_images', to='shop.ImagesForProduct'),
        ),
    ]
