# Generated by Django 3.1.4 on 2020-12-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(blank=True, default='', max_length=12, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(default='', verbose_name='Дата рождения')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
